import { useState } from 'react'
import type { FormEvent } from 'react'
import type { DeliveryProof, DeliveryProofPayload } from '../../types/fieldops'
import { proofStatusOptions, proofTypeOptions } from './badgeLabels'
import type { FieldOpsFormOptions } from './formTypes'

type Props = { proof?: DeliveryProof | null; options: FieldOpsFormOptions; onSubmit: (payload: DeliveryProofPayload) => Promise<void>; onCancel: () => void; isSubmitting?: boolean }

type FormState = Record<string, string | boolean | File | undefined>

function valueOf(value: unknown) { return value === null || value === undefined ? '' : String(value) }

export function DeliveryProofForm({ proof, options, onSubmit, onCancel, isSubmitting }: Props) {
  const [form, setForm] = useState<FormState>({ shipment: valueOf(proof?.shipment), package: valueOf(proof?.package), route: valueOf(proof?.route), route_stop: valueOf(proof?.route_stop), route_shipment: valueOf(proof?.route_shipment), proof_type: proof?.proof_type ?? 'delivery', status: proof?.status ?? 'pending_review', received_by_name: proof?.received_by_name ?? '', received_by_rut: proof?.received_by_rut ?? '', recipient_relationship: proof?.recipient_relationship ?? '', delivery_notes: proof?.delivery_notes ?? '', signature_text: proof?.signature_text ?? '', latitude: valueOf(proof?.latitude), longitude: valueOf(proof?.longitude), location_accuracy_m: valueOf(proof?.location_accuracy_m), location_text: proof?.location_text ?? '', captured_at: proof?.captured_at ? proof.captured_at.slice(0, 16) : '', is_active: proof?.is_active ?? true })
  const set = (key: string, value: string | boolean | File | undefined) => setForm((current) => ({ ...current, [key]: value }))
  const submit = async (event: FormEvent) => { event.preventDefault(); await onSubmit(form) }
  const missingBase = options.shipments.length === 0 && options.routes.length === 0
  return <form onSubmit={submit} className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
    <div className="flex items-center justify-between"><h3 className="text-lg font-bold text-slate-900">{proof ? 'Editar evidencia' : 'Nueva evidencia'}</h3><button type="button" onClick={onCancel} className="text-sm text-slate-500 hover:underline">Cerrar</button></div>
    {missingBase ? <p className="rounded-xl bg-amber-50 px-3 py-2 text-sm text-amber-800">Primero debes crear encomiendas, rutas, conductores o vehículos.</p> : null}
    <div className="grid gap-4 md:grid-cols-3"><Select label="Encomienda" value={String(form.shipment ?? '')} options={options.shipments} onChange={(v) => set('shipment', v)} /><Select label="Bulto" value={String(form.package ?? '')} options={options.packages} onChange={(v) => set('package', v)} /><Select label="Ruta" value={String(form.route ?? '')} options={options.routes} onChange={(v) => set('route', v)} /><Select label="Parada" value={String(form.route_stop ?? '')} options={options.routeStops} onChange={(v) => set('route_stop', v)} /><Select label="Asignación ruta" value={String(form.route_shipment ?? '')} options={options.routeShipments} onChange={(v) => set('route_shipment', v)} /><Select label="Tipo" value={String(form.proof_type)} options={proofTypeOptions} onChange={(v) => set('proof_type', v)} /><Select label="Estado" value={String(form.status)} options={proofStatusOptions} onChange={(v) => set('status', v)} /><Input label="Recibido por" value={String(form.received_by_name ?? '')} onChange={(v) => set('received_by_name', v)} /><Input label="RUT receptor" value={String(form.received_by_rut ?? '')} onChange={(v) => set('received_by_rut', v)} /><Input label="Relación receptor" value={String(form.recipient_relationship ?? '')} onChange={(v) => set('recipient_relationship', v)} /><Input label="Latitud" type="number" value={String(form.latitude ?? '')} onChange={(v) => set('latitude', v)} /><Input label="Longitud" type="number" value={String(form.longitude ?? '')} onChange={(v) => set('longitude', v)} /><Input label="Precisión ubicación (m)" type="number" value={String(form.location_accuracy_m ?? '')} onChange={(v) => set('location_accuracy_m', v)} /><Input label="Ubicación texto" value={String(form.location_text ?? '')} onChange={(v) => set('location_text', v)} /><Input label="Capturado en" type="datetime-local" value={String(form.captured_at ?? '')} onChange={(v) => set('captured_at', v)} /></div>
    <Textarea label="Notas de entrega" value={String(form.delivery_notes ?? '')} onChange={(v) => set('delivery_notes', v)} /><Textarea label="Firma en texto" value={String(form.signature_text ?? '')} onChange={(v) => set('signature_text', v)} />
    <div className="grid gap-4 md:grid-cols-2"><FileInput label="Foto" existing={proof?.photo} onChange={(file) => set('photo', file)} /><FileInput label="Archivo de firma" existing={proof?.signature_file} onChange={(file) => set('signature_file', file)} /></div>
    <label className="flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" checked={Boolean(form.is_active)} onChange={(e: { target: HTMLInputElement }) => set('is_active', e.target.checked)} /> Activa</label>
    <div className="flex gap-2"><button disabled={isSubmitting} className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">Guardar</button><button type="button" onClick={onCancel} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700">Cancelar</button></div>
  </form>
}
function Select({ label, value, options, onChange }: { label: string; value: string; options: { value: string | number; label: string }[]; onChange: (v: string) => void }) { return <label className="space-y-1 text-sm font-medium text-slate-700">{label}<select value={value} onChange={(e: { target: HTMLSelectElement }) => onChange(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2"><option value="">Seleccionar</option>{options.map((option) => <option key={String(option.value)} value={String(option.value)}>{option.label}</option>)}</select></label> }
function Input({ label, value, onChange, type = 'text' }: { label: string; value: string; onChange: (v: string) => void; type?: string }) { return <label className="space-y-1 text-sm font-medium text-slate-700">{label}<input type={type} value={value} onChange={(e: { target: HTMLInputElement }) => onChange(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2" step="any" /></label> }
function Textarea({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) { return <label className="space-y-1 text-sm font-medium text-slate-700">{label}<textarea value={value} onChange={(e: { target: HTMLTextAreaElement }) => onChange(e.target.value)} rows={3} className="w-full rounded-xl border border-slate-200 px-3 py-2" /></label> }
function FileInput({ label, existing, onChange }: { label: string; existing?: string | null; onChange: (file?: File) => void }) { return <label className="space-y-1 text-sm font-medium text-slate-700">{label}<input type="file" onChange={(e: { target: HTMLInputElement }) => onChange(e.target.files?.[0])} className="w-full rounded-xl border border-slate-200 px-3 py-2" />{existing ? <a href={existing} target="_blank" rel="noreferrer" className="block text-xs text-cyan-700 hover:underline">Archivo actual: {existing.split('/').pop()}</a> : null}</label> }
