import type { DeliveryProof } from '../../types/fieldops'
import { DeliveryProofStatusBadge } from './DeliveryProofStatusBadge'
import { DeliveryProofTypeBadge } from './DeliveryProofTypeBadge'

export function DeliveryProofDetailPanel({ proof, onClose }: { proof: DeliveryProof; onClose: () => void }) {
  return <div className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h3 className="text-lg font-bold text-slate-900">Detalle de evidencia</h3><button onClick={onClose} className="text-sm text-slate-500 hover:underline">Cerrar</button></div><div className="flex gap-2"><DeliveryProofTypeBadge type={proof.proof_type} /><DeliveryProofStatusBadge status={proof.status} /></div><div className="grid gap-3 md:grid-cols-2"><Info label="Encomienda" value={proof.shipment_tracking_code} /><Info label="Bulto" value={proof.package_code} /><Info label="Ruta" value={proof.route_code} /><Info label="Parada" value={proof.route_stop_sequence} /><Info label="Asignación" value={proof.route_shipment_status} /><Info label="Receptor" value={proof.received_by_name} /><Info label="RUT receptor" value={proof.received_by_rut} /><Info label="Relación" value={proof.recipient_relationship} /><Info label="Ubicación" value={proof.location_text} /><Info label="Coordenadas" value={proof.latitude && proof.longitude ? `${proof.latitude}, ${proof.longitude}` : undefined} /><Info label="Capturada en" value={proof.captured_at ? new Date(proof.captured_at).toLocaleString() : undefined} /><Info label="Creada por" value={proof.created_by_name} /><Info label="Revisada por" value={proof.reviewed_by_name} /><Info label="Revisada en" value={proof.reviewed_at ? new Date(proof.reviewed_at).toLocaleString() : undefined} /></div><Text label="Notas de entrega" value={proof.delivery_notes} /><Text label="Firma texto" value={proof.signature_text} /><Text label="Notas de revisión" value={proof.review_notes} /><div className="flex flex-wrap gap-3"><FileLink label="Foto" value={proof.photo} /><FileLink label="Firma archivo" value={proof.signature_file} /></div></div>
}
function Info({ label, value }: { label: string; value?: string | number | null }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-semibold uppercase text-slate-400">{label}</p><p className="mt-1 text-sm text-slate-700">{value || '—'}</p></div> }
function Text({ label, value }: { label: string; value?: string | null }) { return <div><p className="text-sm font-semibold text-slate-700">{label}</p><p className="mt-1 rounded-xl bg-slate-50 p-3 text-sm text-slate-600">{value || '—'}</p></div> }
function FileLink({ label, value }: { label: string; value?: string | null }) { return value ? <a href={value} target="_blank" rel="noreferrer" className="rounded-xl bg-cyan-50 px-3 py-2 text-sm font-semibold text-cyan-700 hover:underline">{label}: {value.split('/').pop()}</a> : <span className="rounded-xl bg-slate-50 px-3 py-2 text-sm text-slate-500">{label}: sin archivo</span> }
