import { useState } from 'react'
import type { FormEvent } from 'react'
import type { Incident, IncidentPayload } from '../../types/fieldops'
import { incidentCategoryOptions, incidentSeverityOptions, incidentStatusOptions } from './badgeLabels'
import type { FieldOpsFormOptions } from './formTypes'

type Props = { incident?: Incident | null; options: FieldOpsFormOptions; onSubmit: (payload: IncidentPayload) => Promise<void>; onCancel: () => void; isSubmitting?: boolean }
type FormState = Record<string, string | boolean | File | undefined>
function valueOf(value: unknown) { return value === null || value === undefined ? '' : String(value) }

export function IncidentForm({ incident, options, onSubmit, onCancel, isSubmitting }: Props) {
  const [form, setForm] = useState<FormState>({ shipment: valueOf(incident?.shipment), package: valueOf(incident?.package), route: valueOf(incident?.route), route_stop: valueOf(incident?.route_stop), route_shipment: valueOf(incident?.route_shipment), driver: valueOf(incident?.driver), vehicle: valueOf(incident?.vehicle), incident_code: incident?.incident_code ?? '', category: incident?.category ?? 'other', severity: incident?.severity ?? 'medium', status: incident?.status ?? 'open', title: incident?.title ?? '', description: incident?.description ?? '', resolution_notes: incident?.resolution_notes ?? '', location_text: incident?.location_text ?? '', latitude: valueOf(incident?.latitude), longitude: valueOf(incident?.longitude), occurred_at: incident?.occurred_at ? incident.occurred_at.slice(0, 16) : '', is_active: incident?.is_active ?? true })
  const set = (key: string, value: string | boolean | File | undefined) => setForm((current) => ({ ...current, [key]: value }))
  const submit = async (event: FormEvent) => { event.preventDefault(); await onSubmit(form) }
  const missingBase = options.shipments.length === 0 && options.routes.length === 0 && options.drivers.length === 0 && options.vehicles.length === 0
  return <form onSubmit={submit} className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
    <div className="flex items-center justify-between"><h3 className="text-lg font-bold text-slate-900">{incident ? 'Editar incidencia' : 'Nueva incidencia'}</h3><button type="button" onClick={onCancel} className="text-sm text-slate-500 hover:underline">Cerrar</button></div>
    {missingBase ? <p className="rounded-xl bg-amber-50 px-3 py-2 text-sm text-amber-800">Primero debes crear encomiendas, rutas, conductores o vehículos.</p> : null}
    <div className="grid gap-4 md:grid-cols-3"><Select label="Encomienda" value={String(form.shipment ?? '')} options={options.shipments} onChange={(v) => set('shipment', v)} /><Select label="Bulto" value={String(form.package ?? '')} options={options.packages} onChange={(v) => set('package', v)} /><Select label="Ruta" value={String(form.route ?? '')} options={options.routes} onChange={(v) => set('route', v)} /><Select label="Parada" value={String(form.route_stop ?? '')} options={options.routeStops} onChange={(v) => set('route_stop', v)} /><Select label="Asignación ruta" value={String(form.route_shipment ?? '')} options={options.routeShipments} onChange={(v) => set('route_shipment', v)} /><Select label="Conductor" value={String(form.driver ?? '')} options={options.drivers} onChange={(v) => set('driver', v)} /><Select label="Vehículo" value={String(form.vehicle ?? '')} options={options.vehicles} onChange={(v) => set('vehicle', v)} /><Input label="Código incidencia (opcional)" value={String(form.incident_code ?? '')} onChange={(v) => set('incident_code', v)} /><Select label="Categoría" value={String(form.category)} options={incidentCategoryOptions} onChange={(v) => set('category', v)} /><Select label="Severidad" value={String(form.severity)} options={incidentSeverityOptions} onChange={(v) => set('severity', v)} /><Select label="Estado" value={String(form.status)} options={incidentStatusOptions} onChange={(v) => set('status', v)} /><Input label="Título" value={String(form.title ?? '')} onChange={(v) => set('title', v)} /><Input label="Ubicación" value={String(form.location_text ?? '')} onChange={(v) => set('location_text', v)} /><Input label="Latitud" type="number" value={String(form.latitude ?? '')} onChange={(v) => set('latitude', v)} /><Input label="Longitud" type="number" value={String(form.longitude ?? '')} onChange={(v) => set('longitude', v)} /><Input label="Ocurrió en" type="datetime-local" value={String(form.occurred_at ?? '')} onChange={(v) => set('occurred_at', v)} /></div>
    <Textarea label="Descripción" value={String(form.description ?? '')} onChange={(v) => set('description', v)} /><Textarea label="Notas de resolución" value={String(form.resolution_notes ?? '')} onChange={(v) => set('resolution_notes', v)} />
    <FileInput label="Evidencia adjunta" existing={incident?.evidence_file} onChange={(file) => set('evidence_file', file)} />
    <label className="flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" checked={Boolean(form.is_active)} onChange={(e: { target: HTMLInputElement }) => set('is_active', e.target.checked)} /> Activa</label>
    <div className="flex gap-2"><button disabled={isSubmitting} className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">Guardar</button><button type="button" onClick={onCancel} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700">Cancelar</button></div>
  </form>
}
function Select({ label, value, options, onChange }: { label: string; value: string; options: { value: string | number; label: string }[]; onChange: (v: string) => void }) { return <label className="space-y-1 text-sm font-medium text-slate-700">{label}<select value={value} onChange={(e: { target: HTMLSelectElement }) => onChange(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2"><option value="">Seleccionar</option>{options.map((option) => <option key={String(option.value)} value={String(option.value)}>{option.label}</option>)}</select></label> }
function Input({ label, value, onChange, type = 'text' }: { label: string; value: string; onChange: (v: string) => void; type?: string }) { return <label className="space-y-1 text-sm font-medium text-slate-700">{label}<input type={type} value={value} onChange={(e: { target: HTMLInputElement }) => onChange(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2" step="any" /></label> }
function Textarea({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) { return <label className="space-y-1 text-sm font-medium text-slate-700">{label}<textarea value={value} onChange={(e: { target: HTMLTextAreaElement }) => onChange(e.target.value)} rows={3} className="w-full rounded-xl border border-slate-200 px-3 py-2" /></label> }
function FileInput({ label, existing, onChange }: { label: string; existing?: string | null; onChange: (file?: File) => void }) { return <label className="space-y-1 text-sm font-medium text-slate-700">{label}<input type="file" onChange={(e: { target: HTMLInputElement }) => onChange(e.target.files?.[0])} className="w-full rounded-xl border border-slate-200 px-3 py-2" />{existing ? <a href={existing} target="_blank" rel="noreferrer" className="block text-xs text-cyan-700 hover:underline">Archivo actual: {existing.split('/').pop()}</a> : null}</label> }
