import type { Incident } from '../../types/fieldops'
import { IncidentCategoryBadge } from './IncidentCategoryBadge'
import { IncidentSeverityBadge } from './IncidentSeverityBadge'
import { IncidentStatusBadge } from './IncidentStatusBadge'

export function IncidentDetailPanel({ incident, onClose }: { incident: Incident; onClose: () => void }) {
  return <div className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h3 className="text-lg font-bold text-slate-900">Detalle de incidencia</h3><button onClick={onClose} className="text-sm text-slate-500 hover:underline">Cerrar</button></div><div className="flex flex-wrap gap-2"><IncidentCategoryBadge category={incident.category} /><IncidentSeverityBadge severity={incident.severity} /><IncidentStatusBadge status={incident.status} /></div><div className="grid gap-3 md:grid-cols-2"><Info label="Código" value={incident.incident_code || `#${incident.id}`} /><Info label="Título" value={incident.title} /><Info label="Encomienda" value={incident.shipment_tracking_code} /><Info label="Bulto" value={incident.package_code} /><Info label="Ruta" value={incident.route_code} /><Info label="Parada" value={incident.route_stop_sequence} /><Info label="Conductor" value={incident.driver_name} /><Info label="Vehículo" value={incident.vehicle_plate} /><Info label="Ubicación" value={incident.location_text} /><Info label="Coordenadas" value={incident.latitude && incident.longitude ? `${incident.latitude}, ${incident.longitude}` : undefined} /><Info label="Ocurrió en" value={incident.occurred_at ? new Date(incident.occurred_at).toLocaleString() : undefined} /><Info label="Resuelta en" value={incident.resolved_at ? new Date(incident.resolved_at).toLocaleString() : undefined} /><Info label="Reportada por" value={incident.reported_by_name} /><Info label="Resuelta por" value={incident.resolved_by_name} /></div><Text label="Descripción" value={incident.description} /><Text label="Resolución" value={incident.resolution_notes} />{incident.evidence_file ? <a href={incident.evidence_file} target="_blank" rel="noreferrer" className="inline-flex rounded-xl bg-cyan-50 px-3 py-2 text-sm font-semibold text-cyan-700 hover:underline">Evidencia: {incident.evidence_file.split('/').pop()}</a> : <p className="rounded-xl bg-slate-50 p-3 text-sm text-slate-500">Sin evidencia adjunta.</p>}</div>
}
function Info({ label, value }: { label: string; value?: string | number | null }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-semibold uppercase text-slate-400">{label}</p><p className="mt-1 text-sm text-slate-700">{value || '—'}</p></div> }
function Text({ label, value }: { label: string; value?: string | null }) { return <div><p className="text-sm font-semibold text-slate-700">{label}</p><p className="mt-1 rounded-xl bg-slate-50 p-3 text-sm text-slate-600">{value || '—'}</p></div> }
