// @ts-nocheck
import { useState } from 'react'
import type { GenerateFromRoutePayload, GenerateFromShipmentPayload } from '../../types/documents'
import type { DocumentFormOptions } from './formOptions'
import { getDocumentTypeLabel } from './labels'

type Props = { options: DocumentFormOptions; isSubmitting?: boolean; onGenerateFromRoute: (payload: GenerateFromRoutePayload) => void; onGenerateFromShipment: (payload: GenerateFromShipmentPayload) => void }
const routeTypes = ['route_manifest', 'route_sheet', 'transfer_note'] as const
const shipmentTypes = ['delivery_receipt', 'transfer_note'] as const
export function GenerateDocumentPanel({ options, isSubmitting, onGenerateFromRoute, onGenerateFromShipment }: Props) {
  const [routeId, setRouteId] = useState('')
  const [routeType, setRouteType] = useState<(typeof routeTypes)[number]>('route_manifest')
  const [shipmentId, setShipmentId] = useState('')
  const [shipmentType, setShipmentType] = useState<(typeof shipmentTypes)[number]>('delivery_receipt')
  return <section className="grid gap-4 md:grid-cols-2"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-bold text-slate-950">Generar desde ruta</h3><p className="mt-1 text-sm text-slate-500">Manifiesto, hoja de ruta o nota interna de traslado.</p>{options.routes.length === 0 ? <p className="mt-2 rounded-2xl bg-amber-50 px-3 py-2 text-sm text-amber-800">Primero debes crear rutas, encomiendas o maestros relacionados.</p> : null}<div className="mt-4 grid gap-3"><select className="rounded-xl border border-slate-200 px-3 py-2 text-sm" value={routeId} onChange={(e) => setRouteId(e.target.value)}><option value="">Seleccionar ruta</option>{options.routes.map((option) => <option key={String(option.value)} value={option.value}>{option.label}</option>)}</select><select className="rounded-xl border border-slate-200 px-3 py-2 text-sm" value={routeType} onChange={(e) => setRouteType(e.target.value as typeof routeType)}>{routeTypes.map((type) => <option key={type} value={type}>{getDocumentTypeLabel(type)}</option>)}</select><button disabled={!routeId || isSubmitting} onClick={() => onGenerateFromRoute({ route_id: routeId, document_type: routeType })} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Generar documento de ruta</button></div></div><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-bold text-slate-950">Generar desde encomienda</h3><p className="mt-1 text-sm text-slate-500">Comprobante interno de entrega o nota de traslado.</p>{options.shipments.length === 0 ? <p className="mt-2 rounded-2xl bg-amber-50 px-3 py-2 text-sm text-amber-800">Primero debes crear rutas, encomiendas o maestros relacionados.</p> : null}<div className="mt-4 grid gap-3"><select className="rounded-xl border border-slate-200 px-3 py-2 text-sm" value={shipmentId} onChange={(e) => setShipmentId(e.target.value)}><option value="">Seleccionar encomienda</option>{options.shipments.map((option) => <option key={String(option.value)} value={option.value}>{option.label}</option>)}</select><select className="rounded-xl border border-slate-200 px-3 py-2 text-sm" value={shipmentType} onChange={(e) => setShipmentType(e.target.value as typeof shipmentType)}>{shipmentTypes.map((type) => <option key={type} value={type}>{getDocumentTypeLabel(type)}</option>)}</select><button disabled={!shipmentId || isSubmitting} onClick={() => onGenerateFromShipment({ shipment_id: shipmentId, document_type: shipmentType })} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Generar documento de encomienda</button></div></div></section>
}
