# Generated by Django 5.2.14 on 2026-05-14 22:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("parties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        unique=True,
                        verbose_name="código de tracking",
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="referencia externa"
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(max_length=160, verbose_name="remitente"),
                ),
                (
                    "sender_phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="teléfono remitente"
                    ),
                ),
                (
                    "sender_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email remitente"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(max_length=160, verbose_name="destinatario"),
                ),
                (
                    "recipient_phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="teléfono destinatario"
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email destinatario"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "package_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="cantidad de bultos declarada"
                    ),
                ),
                (
                    "total_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="peso total kg",
                    ),
                ),
                (
                    "total_volume_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="volumen total m3",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("standard", "Estándar"),
                            ("express", "Express"),
                            ("urgent", "Urgente"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="prioridad",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Retiro"),
                            ("delivery", "Entrega"),
                            ("transfer", "Transferencia"),
                        ],
                        default="delivery",
                        max_length=20,
                        verbose_name="tipo de servicio",
                    ),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("received", "Recibida"),
                            ("classified", "Clasificada"),
                            ("ready_for_route", "Lista para ruta"),
                            ("assigned_to_route", "Asignada a ruta"),
                            ("in_transit", "En tránsito"),
                            ("delivered", "Entregada"),
                            ("failed_delivery", "Entrega fallida"),
                            ("returned", "Devuelta"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="draft",
                        max_length=30,
                        verbose_name="estado actual",
                    ),
                ),
                (
                    "requested_delivery_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="fecha solicitada de entrega",
                    ),
                ),
                (
                    "delivery_window_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="inicio ventana de entrega"
                    ),
                ),
                (
                    "delivery_window_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fin ventana de entrega"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="recibida en"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="entregada en"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizada"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="parties.customer",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "destination_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="destination_shipments",
                        to="locations.address",
                        verbose_name="dirección destino",
                    ),
                ),
                (
                    "origin_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="origin_shipments",
                        to="locations.address",
                        verbose_name="dirección origen",
                    ),
                ),
                (
                    "origin_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="origin_shipments",
                        to="locations.warehouse",
                        verbose_name="bodega origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "encomienda",
                "verbose_name_plural": "encomiendas",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "package_code",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        unique=True,
                        verbose_name="código de bulto",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="peso kg",
                    ),
                ),
                (
                    "length_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="largo cm",
                    ),
                ),
                (
                    "width_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="ancho cm",
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="alto cm",
                    ),
                ),
                (
                    "volume_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="volumen m3",
                    ),
                ),
                (
                    "declared_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="valor declarado",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="código de barras"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Recibido"),
                            ("classified", "Clasificado"),
                            ("loaded", "Cargado"),
                            ("in_transit", "En tránsito"),
                            ("delivered", "Entregado"),
                            ("failed_delivery", "Entrega fallida"),
                            ("returned", "Devuelto"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="received",
                        max_length=30,
                        verbose_name="estado",
                    ),
                ),
                (
                    "is_fragile",
                    models.BooleanField(default=False, verbose_name="frágil"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="logistics.shipment",
                        verbose_name="encomienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "bulto",
                "verbose_name_plural": "bultos",
                "ordering": ["shipment__tracking_code", "package_code"],
            },
        ),
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("received", "Recibida"),
                            ("classified", "Clasificada"),
                            ("ready_for_route", "Lista para ruta"),
                            ("assigned_to_route", "Asignada a ruta"),
                            ("in_transit", "En tránsito"),
                            ("delivered", "Entregada"),
                            ("failed_delivery", "Entrega fallida"),
                            ("returned", "Devuelta"),
                            ("cancelled", "Cancelada"),
                        ],
                        max_length=30,
                        verbose_name="estado",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("status_change", "Cambio de estado"),
                            ("manual_note", "Nota manual"),
                            ("system", "Sistema"),
                            ("exception", "Excepción"),
                        ],
                        default="status_change",
                        max_length=30,
                        verbose_name="tipo de evento",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "location_text",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="ubicación"
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="ocurrió en"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracking_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="logistics.package",
                        verbose_name="bulto",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="logistics.shipment",
                        verbose_name="encomienda",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tracking_events",
                        to="locations.warehouse",
                        verbose_name="bodega",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento de tracking",
                "verbose_name_plural": "eventos de tracking",
                "ordering": ["-occurred_at", "-created_at", "-id"],
            },
        ),
    ]
