# Generated by Django 5.2.14 on 2026-05-14 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="código"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "max_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="peso máximo kg",
                    ),
                ),
                (
                    "max_volume_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="volumen máximo m3",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
            ],
            options={
                "verbose_name": "tipo de vehículo",
                "verbose_name_plural": "tipos de vehículo",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("code__isnull", False),
                            models.Q(("code", ""), _negated=True),
                        ),
                        fields=("code",),
                        name="unique_vehicle_type_code_when_present",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="patente"
                    ),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=80, verbose_name="marca"),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=80, verbose_name="modelo"),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="año"
                    ),
                ),
                (
                    "capacity_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="capacidad kg",
                    ),
                ),
                (
                    "capacity_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="capacidad m3",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponible"),
                            ("assigned", "Asignado"),
                            ("maintenance", "Mantención"),
                            ("inactive", "Inactivo"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="fleet.vehicletype",
                        verbose_name="tipo de vehículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "vehículo",
                "verbose_name_plural": "vehículos",
                "ordering": ["plate_number"],
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="nombres"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="apellidos"),
                ),
                (
                    "rut",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="RUT"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="teléfono"
                    ),
                ),
                (
                    "license_class",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="clase de licencia"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponible"),
                            ("assigned", "Asignado"),
                            ("inactive", "Inactivo"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "default_vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_drivers",
                        to="fleet.vehicle",
                        verbose_name="vehículo por defecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "conductor",
                "verbose_name_plural": "conductores",
                "ordering": ["last_name", "first_name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("rut__isnull", False), models.Q(("rut", ""), _negated=True)
                        ),
                        fields=("rut",),
                        name="unique_driver_rut_when_present",
                    )
                ],
            },
        ),
    ]
