# Generated by Django 5.2.14 on 2026-05-16 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="driver_type",
            field=models.CharField(
                choices=[("internal", "Interno"), ("external", "Externo")],
                default="internal",
                max_length=20,
                verbose_name="tipo de conductor",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="location_source",
            field=models.CharField(
                choices=[
                    ("mobile_web", "Web móvil"),
                    ("mobile_app", "App móvil"),
                    ("vehicle_gps", "GPS vehículo"),
                    ("manual", "Manual"),
                    ("unknown", "No definido"),
                ],
                default="mobile_web",
                max_length=20,
                verbose_name="fuente de ubicación",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driver_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuario asociado",
            ),
        ),
    ]
