# Generated by Django 5.2.14 on 2026-05-15 02:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fleet", "0001_initial"),
        ("logistics", "0001_initial"),
        ("routing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proof_type",
                    models.CharField(
                        choices=[
                            ("delivery", "Entrega"),
                            ("failed_delivery", "Entrega fallida"),
                            ("pickup", "Retiro"),
                            ("return", "Devolución"),
                        ],
                        default="delivery",
                        max_length=30,
                        verbose_name="tipo de evidencia",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pendiente de revisión"),
                            ("accepted", "Aceptada"),
                            ("rejected", "Rechazada"),
                        ],
                        default="pending_review",
                        max_length=30,
                        verbose_name="estado",
                    ),
                ),
                (
                    "received_by_name",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="recibido por"
                    ),
                ),
                (
                    "received_by_rut",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="RUT receptor"
                    ),
                ),
                (
                    "recipient_relationship",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        verbose_name="relación con destinatario",
                    ),
                ),
                (
                    "delivery_notes",
                    models.TextField(
                        blank=True, verbose_name="observaciones de entrega"
                    ),
                ),
                (
                    "photo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="delivery_proofs/photos/",
                        verbose_name="foto",
                    ),
                ),
                (
                    "signature_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="delivery_proofs/signatures/",
                        verbose_name="archivo de firma",
                    ),
                ),
                (
                    "signature_text",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="firma textual"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="latitud",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="longitud",
                    ),
                ),
                (
                    "location_accuracy_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="precisión ubicación m",
                    ),
                ),
                (
                    "location_text",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="ubicación"
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="capturada en"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="revisada en"
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, verbose_name="notas de revisión"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizada"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_delivery_proofs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creada por",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_proofs",
                        to="logistics.package",
                        verbose_name="bulto",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_delivery_proofs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="revisada por",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_proofs",
                        to="routing.route",
                        verbose_name="ruta",
                    ),
                ),
                (
                    "route_shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_proofs",
                        to="routing.routeshipment",
                        verbose_name="encomienda en ruta",
                    ),
                ),
                (
                    "route_stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_proofs",
                        to="routing.routestop",
                        verbose_name="parada de ruta",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_proofs",
                        to="logistics.shipment",
                        verbose_name="encomienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "evidencia de entrega",
                "verbose_name_plural": "evidencias de entrega",
                "ordering": ["-captured_at", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_code",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        unique=True,
                        verbose_name="código de incidencia",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("customer_absent", "Cliente ausente"),
                            ("wrong_address", "Dirección incorrecta"),
                            ("damaged_package", "Paquete dañado"),
                            ("rejected_by_recipient", "Rechazado por destinatario"),
                            ("inaccessible_zone", "Zona inaccesible"),
                            ("vehicle_issue", "Problema de vehículo"),
                            ("partial_delivery", "Entrega parcial"),
                            ("rescheduled", "Reprogramado"),
                            ("returned_to_warehouse", "Devuelto a bodega"),
                            ("lost_package", "Paquete extraviado"),
                            ("other", "Otro"),
                        ],
                        default="other",
                        max_length=40,
                        verbose_name="categoría",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("critical", "Crítica"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="severidad",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Abierta"),
                            ("in_review", "En revisión"),
                            ("resolved", "Resuelta"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="título")),
                ("description", models.TextField(verbose_name="descripción")),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="notas de resolución"),
                ),
                (
                    "location_text",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="ubicación"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="latitud",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="longitud",
                    ),
                ),
                (
                    "evidence_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="incidents/evidence/",
                        verbose_name="archivo de evidencia",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="ocurrió en"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="resuelta en"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizada"),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="fleet.driver",
                        verbose_name="conductor",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="logistics.package",
                        verbose_name="bulto",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_incidents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reportada por",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_incidents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="resuelta por",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="routing.route",
                        verbose_name="ruta",
                    ),
                ),
                (
                    "route_shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="routing.routeshipment",
                        verbose_name="encomienda en ruta",
                    ),
                ),
                (
                    "route_stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="routing.routestop",
                        verbose_name="parada de ruta",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="logistics.shipment",
                        verbose_name="encomienda",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="fleet.vehicle",
                        verbose_name="vehículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "incidencia operativa",
                "verbose_name_plural": "incidencias operativas",
                "ordering": ["-occurred_at", "-created_at", "-id"],
            },
        ),
    ]
