# Generated by Django 5.2.14 on 2026-05-14 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nombre")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="código"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
            ],
            options={
                "verbose_name": "zona",
                "verbose_name_plural": "zonas",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("code__isnull", False),
                            models.Q(("code", ""), _negated=True),
                        ),
                        fields=("code",),
                        name="unique_zone_code_when_present",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=160, verbose_name="nombre")),
                ("street", models.CharField(max_length=160, verbose_name="calle")),
                (
                    "number",
                    models.CharField(blank=True, max_length=30, verbose_name="número"),
                ),
                (
                    "apartment",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="departamento/oficina"
                    ),
                ),
                ("commune", models.CharField(max_length=100, verbose_name="comuna")),
                ("city", models.CharField(max_length=100, verbose_name="ciudad")),
                ("region", models.CharField(max_length=100, verbose_name="región")),
                (
                    "country",
                    models.CharField(
                        default="Chile", max_length=80, verbose_name="país"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="código postal"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="latitud",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="longitud",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="addresses",
                        to="locations.zone",
                        verbose_name="zona",
                    ),
                ),
            ],
            options={
                "verbose_name": "dirección",
                "verbose_name_plural": "direcciones",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140, verbose_name="nombre")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="código"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="teléfono"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses",
                        to="locations.address",
                        verbose_name="dirección",
                    ),
                ),
            ],
            options={
                "verbose_name": "bodega",
                "verbose_name_plural": "bodegas",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("code__isnull", False),
                            models.Q(("code", ""), _negated=True),
                        ),
                        fields=("code",),
                        name="unique_warehouse_code_when_present",
                    )
                ],
            },
        ),
    ]
