# Generated by Django 5.2.14 on 2026-05-15 05:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fieldops", "0001_initial"),
        ("fleet", "0001_initial"),
        ("locations", "0001_initial"),
        ("logistics", "0001_initial"),
        ("parties", "0001_initial"),
        ("routing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogisticsDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        unique=True,
                        verbose_name="folio interno",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("transfer_note", "Nota interna de traslado"),
                            ("route_manifest", "Manifiesto de carga"),
                            ("route_sheet", "Hoja de ruta"),
                            ("delivery_receipt", "Comprobante interno de entrega"),
                            ("incident_report", "Informe interno de incidencia"),
                            ("internal_note", "Nota interna"),
                        ],
                        max_length=30,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("issued", "Emitido"),
                            ("cancelled", "Anulado"),
                            ("archived", "Archivado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("title", models.CharField(max_length=180, verbose_name="título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="fecha de emisión",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="emitido en"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="anulado en"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="archivado en"
                    ),
                ),
                (
                    "origin_text",
                    models.CharField(blank=True, max_length=240, verbose_name="origen"),
                ),
                (
                    "destination_text",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="destino"
                    ),
                ),
                (
                    "customer_name_snapshot",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="cliente snapshot"
                    ),
                ),
                (
                    "driver_name_snapshot",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="conductor snapshot"
                    ),
                ),
                (
                    "vehicle_plate_snapshot",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="patente snapshot"
                    ),
                ),
                (
                    "route_code_snapshot",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="código ruta snapshot"
                    ),
                ),
                (
                    "shipment_tracking_code_snapshot",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="tracking snapshot"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "internal_observations",
                    models.TextField(blank=True, verbose_name="observaciones internas"),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="referencia externa"
                    ),
                ),
                (
                    "sii_reference",
                    models.CharField(
                        blank=True,
                        help_text="Referencia manual a documento externo/SII. No emite documentos tributarios reales.",
                        max_length=100,
                        verbose_name="referencia SII manual",
                    ),
                ),
                (
                    "total_shipments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total encomiendas"
                    ),
                ),
                (
                    "total_packages",
                    models.PositiveIntegerField(default=0, verbose_name="total bultos"),
                ),
                (
                    "total_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="peso total kg",
                    ),
                ),
                (
                    "total_volume_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="volumen total m3",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/attachments/",
                        verbose_name="adjunto",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_logistics_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="anulado por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_logistics_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logistics_documents",
                        to="parties.customer",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "delivery_proof",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logistics_documents",
                        to="fieldops.deliveryproof",
                        verbose_name="evidencia",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logistics_documents",
                        to="fleet.driver",
                        verbose_name="conductor",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logistics_documents",
                        to="fieldops.incident",
                        verbose_name="incidencia",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_logistics_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="emitido por",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logistics_documents",
                        to="routing.route",
                        verbose_name="ruta",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logistics_documents",
                        to="logistics.shipment",
                        verbose_name="encomienda",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logistics_documents",
                        to="fleet.vehicle",
                        verbose_name="vehículo",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logistics_documents",
                        to="locations.warehouse",
                        verbose_name="bodega",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento logístico interno",
                "verbose_name_plural": "documentos logísticos internos",
                "ordering": ["-issue_date", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LogisticsDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_number",
                    models.PositiveIntegerField(verbose_name="número de línea"),
                ),
                ("description", models.TextField(verbose_name="descripción")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        max_digits=10,
                        verbose_name="cantidad",
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="peso kg",
                    ),
                ),
                (
                    "volume_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="volumen m3",
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="referencia"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="documents.logisticsdocument",
                        verbose_name="documento",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_lines",
                        to="logistics.package",
                        verbose_name="bulto",
                    ),
                ),
                (
                    "route_stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_lines",
                        to="routing.routestop",
                        verbose_name="parada",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_lines",
                        to="logistics.shipment",
                        verbose_name="encomienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "línea de documento logístico",
                "verbose_name_plural": "líneas de documentos logísticos",
                "ordering": ["document", "line_number", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("document", "line_number"),
                        name="unique_active_logistics_document_line_number",
                    )
                ],
            },
        ),
    ]
