# Generated by Django 5.2.14 on 2026-05-15 01:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fleet", "0001_initial"),
        ("locations", "0001_initial"),
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "route_code",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        unique=True,
                        verbose_name="código de ruta",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=160, verbose_name="nombre"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "route_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="fecha de ruta",
                    ),
                ),
                (
                    "planned_start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="inicio planificado"
                    ),
                ),
                (
                    "planned_end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fin planificado"
                    ),
                ),
                (
                    "actual_start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="inicio real"
                    ),
                ),
                (
                    "actual_end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fin real"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("planned", "Planificada"),
                            ("assigned", "Asignada"),
                            ("loaded", "Cargada"),
                            ("in_progress", "En progreso"),
                            ("completed", "Completada"),
                            ("cancelled", "Cancelada"),
                            ("with_incidents", "Con incidencias"),
                        ],
                        default="draft",
                        max_length=30,
                        verbose_name="estado",
                    ),
                ),
                (
                    "estimated_distance_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="distancia estimada km",
                    ),
                ),
                (
                    "estimated_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="duración estimada minutos"
                    ),
                ),
                (
                    "total_shipments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total encomiendas"
                    ),
                ),
                (
                    "total_packages",
                    models.PositiveIntegerField(default=0, verbose_name="total bultos"),
                ),
                (
                    "total_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="peso total kg",
                    ),
                ),
                (
                    "total_volume_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="volumen total m3",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizada"),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes",
                        to="fleet.driver",
                        verbose_name="conductor",
                    ),
                ),
                (
                    "origin_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routes",
                        to="locations.warehouse",
                        verbose_name="bodega origen",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes",
                        to="fleet.vehicle",
                        verbose_name="vehículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "ruta",
                "verbose_name_plural": "rutas",
                "ordering": ["-route_date", "route_code"],
            },
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(verbose_name="secuencia")),
                (
                    "stop_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Retiro"),
                            ("delivery", "Entrega"),
                            ("transfer", "Transferencia"),
                            ("warehouse", "Bodega"),
                            ("return", "Retorno"),
                        ],
                        default="delivery",
                        max_length=20,
                        verbose_name="tipo de parada",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("arrived", "Arribada"),
                            ("completed", "Completada"),
                            ("failed", "Fallida"),
                            ("skipped", "Saltada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "planned_arrival_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="llegada planificada"
                    ),
                ),
                (
                    "actual_arrival_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="llegada real"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completada en"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="nombre contacto"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="teléfono contacto"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="instrucciones"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizada"),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="route_stops",
                        to="locations.address",
                        verbose_name="dirección",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="routing.route",
                        verbose_name="ruta",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="route_stops",
                        to="locations.zone",
                        verbose_name="zona",
                    ),
                ),
            ],
            options={
                "verbose_name": "parada de ruta",
                "verbose_name_plural": "paradas de ruta",
                "ordering": ["route", "sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="RouteShipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="asignada en"
                    ),
                ),
                (
                    "loaded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cargada en"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="entregada en"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Asignada"),
                            ("loaded", "Cargada"),
                            ("in_transit", "En tránsito"),
                            ("delivered", "Entregada"),
                            ("failed_delivery", "Entrega fallida"),
                            ("returned", "Devuelta"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="assigned",
                        max_length=30,
                        verbose_name="estado",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizada"),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_shipments",
                        to="routing.route",
                        verbose_name="ruta",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="route_assignments",
                        to="logistics.shipment",
                        verbose_name="encomienda",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="route_shipments",
                        to="routing.routestop",
                        verbose_name="parada",
                    ),
                ),
            ],
            options={
                "verbose_name": "encomienda en ruta",
                "verbose_name_plural": "encomiendas en ruta",
                "ordering": ["route", "stop__sequence", "assigned_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="routestop",
            constraint=models.UniqueConstraint(
                fields=("route", "sequence"), name="unique_route_stop_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="routeshipment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("route", "shipment"),
                name="unique_active_route_shipment_per_route",
            ),
        ),
    ]
